export { IStorage } from '@application/shared/IStorage'
export { IDocument } from '@application/shared/IDocument'
export { INavigator } from '@application/shared/INavigator'
export { IPriceChecker } from '@application/shared/IPriceChecker'
export { IItemBuyer } from '@application/shared/IItemBuyer'
export { IInventory } from '@application/shared/IInventory'
