const BASE = 'https://www.neopets.com/objects.phtml?type=shop&obj_type=';


const shopData = [
  { "id": 1, "name": "Food Shop" },
  { "id": 2, "name": "Magical Shop" },
  { "id": 3, "name": "Toy Shop" },
  { "id": 4, "name": "Clothes Shop" },
  { "id": 5, "name": "Grooming Shop" },
  { "id": 7, "name": "Book Shop" },
  { "id": 8, "name": "Collectable Card Shop" },
  { "id": 9, "name": "Battle Magic Shop" },
  { "id": 10, "name": "Defense Magic Shop" },
  { "id": 12, "name": "Garden Centre" },
  { "id": 13, "name": "Neopian Pharmacy" },
  { "id": 14, "name": "Chocolate Factory" },
  { "id": 15, "name": "Bakery" },
  { "id": 16, "name": "Healthy Food" },
  { "id": 17, "name": "Neopian Gift Shop" },
  { "id": 18, "name": "Smoothie Store" },
  { "id": 20, "name": "Tropical Food" },
  { "id": 21, "name": "Tiki Tack" },
  { "id": 22, "name": "Grundos" },
  { "id": 23, "name": "Space Weaponry" },
  { "id": 24, "name": "Space Armour" },
  { "id": 25, "name": "Neopian Petpet Shop" },
  { "id": 26, "name": "Robopet Shop" },
  { "id": 27, "name": "Rock Pool" },
  { "id": 30, "name": "Spooky Food" },
  { "id": 31, "name": "Spooky Pets" },
  { "id": 34, "name": "Ye Olde Coffee Shop" },
  { "id": 35, "name": "Slushie Shop" },
  { "id": 36, "name": "Ice Crystal Shop" },
  { "id": 37, "name": "Icy Fun Snow Shop" },
  { "id": 38, "name": "Faerieland bookshop" },
  { "id": 39, "name": "Faerie Food" },
  { "id": 40, "name": "Faerieland Petpets" },
  { "id": 41, "name": "Neopian Furniture" },
  { "id": 42, "name": "Tyrannian Food" },
  { "id": 43, "name": "Tyrannian Furniture" },
  { "id": 44, "name": "Tyrannian Petpets" },
  { "id": 45, "name": "Tyrannian Weaponry" },
  { "id": 46, "name": "Hubert's Hot Dog" },
  { "id": 47, "name": "Pizzaroo" },
  { "id": 48, "name": "Usuki Land" },
  { "id": 49, "name": "Food of the Lost Desert" },
  { "id": 50, "name": "Peopatra's Pet Pets" },
  { "id": 51, "name": "Sutek's Scrolls" },
  { "id": 53, "name": "Back to School Shop" },
  { "id": 54, "name": "Battle Supplies" },
  { "id": 55, "name": "Osiri's Pottery" },
  { "id": 56, "name": "Merifoods" },
  { "id": 57, "name": "Ye Olde Petpets" },
  { "id": 58, "name": "Neopian Post Office Kiosk" },
  { "id": 59, "name": "Haunted Weaponry" },
  { "id": 60, "name": "Spooky Furniture" },
  { "id": 61, "name": "Wintery Petpet" },
  { "id": 62, "name": "Jelly Food" },
  { "id": 63, "name": "Refreshments" },
  { "id": 66, "name": "Kiko Lake Treats" },
  { "id": 67, "name": "Kik0 Lake Carpentry" },
  { "id": 68, "name": "Collectable Coins" },
  { "id": 69, "name": "Petpet Supplies" },
  { "id": 70, "name": "Booktastic Books" },
  { "id": 71, "name": "Kreludan Homes" },
  { "id": 72, "name": "Cafe Kreludor" },
  { "id": 73, "name": "Kayla's Potion Shop" },
  { "id": 74, "name": "Darigan Toys" },
  { "id": 75, "name": "Faerie Furniture" },
  { "id": 76, "name": "Roo Island Marchandise Shop" },
  { "id": 77, "name": "Brightval Books" },
  { "id": 78, "name": "The Scrollery" },
  { "id": 79, "name": "Brightvale Glaziers" },
  { "id": 80, "name": "Brightvale Armoury" },
  { "id": 81, "name": "Brightvale Fruits" },
  { "id": 82, "name": "Brightvale Motery" },
  { "id": 83, "name": "Royal Potionery" },
  { "id": 84, "name": "Neopian Music Shop" },
  { "id": 85, "name": "Lost Desert Medicine" },
  { "id": 86, "name": "Collectable Sea Shells" },
  { "id": 87, "name": "Maractite Marvels" },
  { "id": 88, "name": "Maraquan Petpet" },
  { "id": 89, "name": "Geraptiku Petpets" },
  { "id": 90, "name": "Qasalan Delights" },
  { "id": 91, "name": "Desert Arms" },
  { "id": 92, "name": "Words of Antiquity" },
  { "id": 93, "name": "Faerie Weapon Shop" },
  { "id": 94, "name": "Illustrious Armoury" },
  { "id": 95, "name": "Exquisite Ambrosia" },
  { "id": 96, "name": "Magical Marvels" },
  { "id": 97, "name": "Legendary Petpets" },
  { "id": 98, "name": "Plushie Palace" },
  { "id": 99, "name": "Altador Cup Souvenirs" },
  { "id": 100, "name": "Wonderous Weaponry" },
  { "id": 101, "name": "Exotic Foods" },
  { "id": 102, "name": "Remarkable Restoratives" },
  { "id": 103, "name": "Fanciful Fauna" },
  { "id": 104, "name": "Chesterdrawers' Antiques" },
  { "id": 105, "name": "The Crumpetmonger" },
  { "id": 106, "name": "Neovian Printing Press" },
  { "id": 107, "name": "Prigpants & Swolthy, Tailors" },
  { "id": 108, "name": "Mystical Surroundings" },
  { "id": 109, "name": "Petpetpet Habitat" },
  { "id": 110, "name": "Lampwyck's Lights Fantastic" },
  { "id": 111, "name": "Cog's Togs" },
  { "id": 112, "name": "Molten Morsels" },
  { "id": 113, "name": "Moltaran Petpets" },
  { "id": 114, "name": "Moltaran Books" },
  { "id": 116, "name": "Springy Things" },
  { "id": 117, "name": "Ugga Shinies" }
]

export const NEOPETS_SHOPS: Record<string, {name: string, url: string}> = Object.fromEntries(shopData.map(record => ([record.id.toString(), {name: record.name, url: `${BASE}${record.id}`}])))
